spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bank
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    user: root
    password: password
    default-schema: bank
    baselineOnMigrate: true
    locations: classpath:/db/migration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8080